setup.py: Restrict filebrowser_safe < 0.2.30
Avoid:

  $ ./manage.py runserver
  Validating models...

  0 errors found
  Django version 1.4.2, using settings 'env.bh_dev'
  Development server is running at http://127.0.0.1:8000/
  Quit the server with CONTROL-C.
  django.request - ERROR 2014-01-02 14:17:32,211 base 27583 Internal Server Error: /
  Traceback (most recent call last):
    File "/.../django/core/handlers/base.py", line 105, in get_response
      response = middleware_method(request, callback, callback_args, callback_kwargs)
    File "/.../mezzanine/pages/middleware.py", line 39, in process_view
      for_user=request.user, include_login_required=True)
    File "/.../mezzanine/pages/managers.py", line 56, in with_ascendants_for_slug
      slugs = [home_slug()]
    File "/.../mezzanine/utils/urls.py", line 31, in home_slug
      slug = reverse("home")
    File "/.../django/core/urlresolvers.py", line 476, in reverse
      return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
    File "/.../django/core/urlresolvers.py", line 363, in _reverse_with_prefix
      possibilities = self.reverse_dict.getlist(lookup_view)
    File "/.../django/core/urlresolvers.py", line 276, in reverse_dict
      self._populate()
    File "/.../django/core/urlresolvers.py", line 253, in _populate
      for name in pattern.reverse_dict:
    File "/.../django/core/urlresolvers.py", line 276, in reverse_dict
      self._populate()
    File "/.../django/core/urlresolvers.py", line 253, in _populate
      for name in pattern.reverse_dict:
    File "/.../django/core/urlresolvers.py", line 276, in reverse_dict
      self._populate()
    File "/.../django/core/urlresolvers.py", line 265, in _populate
      lookups.appendlist(pattern.callback, (bits, p_pattern, pattern.default_args))
    File "/.../django/core/urlresolvers.py", line 216, in callback
      self._callback = get_callable(self._callback_str)
    File "/.../django/utils/functional.py", line 27, in wrapper
      result = func(*args)
    File "/.../django/core/urlresolvers.py", line 92, in get_callable
      lookup_view = getattr(import_module(mod_name), func_name)
    File "/.../django/utils/importlib.py", line 35, in import_module
      __import__(name)
    File "/.../filebrowser_safe/views.py", line 34, in <module>
      from filebrowser_safe.decorators import flash_login_required
    File "/.../filebrowser_safe/decorators.py", line 6, in <module>
      from mezzanine.utils.models import get_user_model
  ImportError: cannot import name get_user_model

The get_user_model import was added to filebrowser-safe in 4a47610
(Support for custom user models. Closes #26, 2013-10-11), released in
0.2.30.  Our Azure-specific Mezzanine fork is not compatible, so claim
that explicitly.